
all:
	g++ -g -c -DARDUINO=152 Board_WS2801.cpp
	g++ -g -c -DARDUINO=152 Adafruit_GFX.cpp
	g++ -g -c -DARDUINO=152 Print.cpp
#	g++ -c -DARDUINO=152 -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/variants/mega -I/Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/libraries/SPI -I/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/avr/include/ Board_WS2801.cpp
